# Eastwood-style prompt
format = """
$git_status$git_branch$directory$character"""

[directory]
format = "[$path ]($style)"
style = "cyan"
truncation_length = 5

[character]
success_symbol = "[\\$](bold white)"
error_symbol = "[\\$](bold red)"

[git_branch]
format = "[\\[$branch\\]]($style)"
style = "green"

[git_status]
format = "[$all_status]($style)"
style = "red"
conflicted = "*"
ahead = ""
behind = ""
diverged = ""
untracked = "*"
stashed = ""
modified = "*"
staged = "*"
renamed = "*"
deleted = "*"
